Feature/courses create
Poketnans/sume-free-share pull request #51
Opened 2022-04-26 11:31 UTC by BeatrixFox

2022-04-27 01:47 UTC, Poketnans requested changes
Alguns ajustes a fazer.

2022-04-27 01:47 UTC, Poketnans commented on src/services/Course/createCourseService.ts
> +    );
É necessário criar uma instância de `Course` e preencher suas propriedades. Usar o `id_mode` que vem no request para pesquisar o `CourseMode` e colocar na propriedade `mode` do curso, o mesmo com `period`, `category`, `user_owner`, etc.. Tudo isso antes de passar a nova instância de `Course` para que seja salva pelo método `saveCourse`.

2022-04-27 01:47 UTC, Poketnans commented on src/routes/coursesRoutes.ts
> +  createCourseController
Esta rota é autenticada. Falta usar o middleware de autenticação.

2022-04-28 12:41 UTC, Poketnans approved these changes

2022-04-28 13:08 UTC, Poketnans approved these changes

2022-04-28 13:14 UTC, Brunoro811 approved these changes

2022-04-28 13:15 UTC, merged