fea: finish upadte review
Poketnans/sume-free-share pull request #62
Opened 2022-04-26 20:41 UTC by Brunoro811

2022-04-26 21:13 UTC, Poketnans requested changes
Alguns pontos a ajustar.

2022-04-26 21:13 UTC, Poketnans commented on src/services/Review/updateReview.services.ts
> +    return await objectCourseReview.findOneOrFail(id);
Não é um problema, mas ao invés do `Repo.update()` no método `updateReview()`, pode ser usado o `Repo.save()`, que já retorna a entidade atualizada. Dessa forma não seria necessário rodar um outro método de busca.
https://stackoverflow.com/questions/47792808/typeorm-update-item-and-return-it

2022-04-26 21:13 UTC, Poketnans commented on src/routes/reviewsRoutes.ts
> +reviewsRoutes.patch("/:id", updateReviewController)
Necessário criar um middleware para verificação da permissão. Já tem Task referente criada. Se possível pega, para poder concluir esta rota.
https://www.notion.so/Middleware-de-permiss-o-CourseReview-fc31f8877e1141c3844c134a8bea2ab6

2022-04-26 21:13 UTC, Poketnans commented on src/services/Review/updateReview.services.ts
> +    throw new ErrorHandler(400,`${e.message}`);
Não tem tratativa de erro com o código 400. Necessário tratar o erro NOT FOUND ( 404 ).

2022-04-27 18:00 UTC, Poketnans requested changes

2022-04-27 18:00 UTC, Poketnans commented on src/middlewares/validateAuthReview.middleware.ts
> +
O middleware de validação de autenticação já faz a lógica sobre o token e já insere as informações do usuário no objeto request. Usar isso para não precisar repetir lógica.

2022-04-27 19:39 UTC, Poketnans approved these changes

2022-04-27 19:41 UTC, pedromenimen approved these changes

2022-04-27 19:41 UTC, merged